### ISSUE TITLE
[Bug] Ratio Gráfico 6 casos nuevos por test parece ser el inverso

### ISSUE THREAD

**Issue by fjprobos** [gdiazc/obs-covid-cl#3]
Aparentemente el ratio parece haber sido calculado inversamente a lo que se declara en el título. No parece razonable que haya más casos confirmados por PCR que la cantidad de test de este tipo. Creo que hay que corregir el título a Cantidad de test por casos nuevos, o bien invertir el cálculo. Sugiero lo segundo ya que coincide con el dato de % de posibilidad que declara diariamente el MINSAL. @gdiazc confirma o descarta por favor mi sospecha, yo puedo tomar el arreglo.

![image](https://user-images.githubusercontent.com/3968323/80919789-ec940f80-8d39-11ea-970d-1bc61d9c37fe.png)

**Comment by gdiazc** [comment]
Muchas gracias! Modifiqué el gráfico. Avísame si crees que arreglé el problema!

**Comment by fjprobos** [comment]
Se ve clarísimo ahora. Gracias!
